![Picture title](image-20211013-103633.png)

How to convert a list to Numpy array

In [4]:
import numpy as np
a=[123,456,431,45,4566,23,80,34]
a=np.array(a)

array([ 123,  456,  431,   45, 4566,   23,   80,   34])

Operation on numpy arrays

In [7]:
b=[123,456,431,10,45,23,80,43]
b=np.array(b)
a+b , a*b , a-b

(array([ 246,  912,  862,   55, 4611,   46,  160,   77]),
 array([ 15129, 207936, 185761,    450, 205470,    529,   6400,   1462]),
 array([   0,    0,    0,   35, 4521,    0,    0,   -9]),
 array([  1.        ,   1.        ,   1.        ,   4.5       ,
        101.46666667,   1.        ,   1.        ,   0.79069767]))

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c59b36c5-ab6e-4716-ae2f-508a35cac12a' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>